DO $$ BEGIN
 CREATE TYPE "public"."blog_status" AS ENUM('in_progress', 'contacted', 'failed');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "thanks-tech-blog_technical-blog" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thanks-tech-blog_technical-blog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar(2048) NOT NULL,
	"comment" text,
	"status" "blog_status" DEFAULT 'in_progress' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "thanks-tech-blog_post";--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "url_idx" ON "thanks-tech-blog_technical-blog" USING btree ("url");